name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.2
          - 3.1
          - "3.0"
          - 2.7
          - 2.6
          - 2.5
        rails-version:
          # - "edge"
          - 7
          - 6.1
          - "6.0"
        exclude:
          # Rails 7 requires Ruby 2.7+
          - ruby-version: 2.5
            rails-version: 7
          - ruby-version: 2.6
            rails-version: 7
          # Rails 6 requires Ruby <= 3.0
          - ruby-version: 3.1
            rails-version: "6.0"
          - ruby-version: 3.2
            rails-version: "6.0"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run gem tests
        run: |
          bundle config set --local path '/tmp/gem-tests'
          bundle
          bundle exec rake
      - name: Set up new Rails dummy app
        run: |
          bin/dummy-app-setup ${{ matrix.rails-version }}
      - name: Run Rails dummy app tests
        run: |
          bundle exec rails db:drop db:create db:migrate spec
