name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2
          - 3.1
          - 3.0
          - 2.7
        gemfile:
          - Gemfile-rails-7
          - Gemfile-rails-6.1
          - Gemfile-rails-6.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run gem tests
        run: |
          bundle
          bundle exec rake
      - name: Run Rails dummy app tests
        working-directory: ./spec/dummy_app
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
        run: |
          bundle
          bundle exec rake
